exception InvalidKey {};

interface Etcd {

    // atributos
    readonly attribute string id;
    attribute Map<string,string> table_;

    //operações
    void put(in string key, in string val);
    string get(in string key) raises (InvalidKey);
    void del(in string key) raises (InvalidKey);
    oneway void shutdown(in string senha);
};

